name: sail_in_co
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  provider: ^6.1.5+1
  logger: ^2.6.2
  connectivity_plus: ^7.0.0
  intl: ^0.20.2
  path_provider: ^2.1.5
  image_picker: ^1.2.0
  image: ^4.5.4
  flutter_svg: ^2.2.1
  fl_chart: ^1.1.1
  liquid_pull_to_refresh: ^3.0.1
  flutter_localization: ^0.3.3
  shared_preferences: ^2.5.3
  auto_size_text: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.8.0
  json_serializable: ^6.11.1


flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/

flutter_gen_l10n:
  enabled: true
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
  output-dir: lib/l10n/generated
  output-localization-file: app_localizations.dart
  synthetic-package: false
